# We are creating new Security Group, and updating the SG of the existing instance.
Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-afd15ed0
      InstanceType: t2.micro
      KeyName: custodian
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: subnet-fd4dbf9a
      Tags:
        - Key: Name
          Value: !Join [ " ", [host-amazon-linux-cf-test-1]]
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: eden-cf-sg
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      VpcId: vpc-97b4ffec