Parameters:
  
  NameOfInstance:
    Description: "The name for your EC2 instance."
    Type: String

  SubnetIds:
    Description: "Select appropriate subnet for the AMIs."
    Type: String
    Default: subnet-fd4dbf9a
    AllowedValues:
      - subnet-fd4dbf9a
      - subnet-8d29f1d1

  InstanceTypeParameter:
    Description: "Choose from t2.micro, m1.small or m1.large. Default is t2.micro."
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large

  GeneralBilling:
    Description: "Enter Finance, IT, DevOps or InfoSecurity. Default is InfoSecurity."
    Type: String
    Default: InfoSecurity
    AllowedValues:
      - DevOps
      - IT
      - Finance
      - InfoSecurity

Mappings:
  RegionMap:
    us-east-2: 
      AMI: ami-922914f7
    us-west-1:
      AMI: ami-00d8c660
    us-east-1:
      AMI: ami-afd15ed0

Resources:

  Ec2Instance:
    Type: "AWS::EC2::Instance"

    Properties:

      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI

      InstanceType: !Ref InstanceTypeParameter

      SubnetId: !Ref SubnetIds

      Tags:

        - Key: Name
          Value: !Ref NameOfInstance

        - Key: BillingDepartment
          Value: !Ref GeneralBilling

Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref Ec2Instance
  PrivateIP:
    Value: !GetAtt
    - Ec2Instance
    - PrivateIp
  PrivateDNS:
    Value: !GetAtt
    - Ec2Instance
    - PrivateDnsName
  PublicDNS:             # the subnet setting for allocation of Public IP must be enabled
    Value: !GetAtt
    - Ec2Instance
    - PublicDnsName
  PublicIP:              # same as PublicDNS, needs 'Public Subnet'
    Value: !GetAtt
    - Ec2Instance
    - PublicIp
  AZ:
    Value: !GetAtt
    - Ec2Instance
    - AvailabilityZone