AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template S3_Bucket_With_Tags: Sample template
  showing how to create a publicly accessible S3 bucket that has tags.
  **WARNING** This template creates an S3 bucket. You will be billed for the AWS
  resources used if you create a stack from this template.
Parameters:
  NameOfBucket:
    Description: "Enter S3 bucket name."
    Type: String
  BillingTag:
    Description: "Which department will this be billed for?"
    Type: String
  BucketOwner:
    Description: "Which department does own this bucket?"
    Type: String
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref NameOfBucket
      AccessControl: PublicRead
      Tags:
        - Key: Owner
          Value: !Ref BucketOwner
        - Key: Billing
          Value: !Ref BillingTag
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of S3 bucket.